### ISSUE TITLE
Provider configurator dialog - error appears after selecting a group in the group-selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-oidc-idprovider#74]
1. Open wizard for new ID provider.
2. Select `OIDC ID Provider`.
3. Click on edit icon and open the configurator dialog.
4. Expand the `Default groups` selector

BUG: error appears in the selector 
![image](https://user-images.githubusercontent.com/3728712/152947183-d445e67e-cd43-4901-9636-d394da540c14.png)

**Comment by rymsha** [comment]
We don't have UI configuration anymore
